language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.1

script:
- RAILS_ENV=test bundle exec rake --trace db:create db:migrate

notifications:
  email:
    recipients:
      - steven.magelowitz@gmail.com
    on_failure: change
    on_success: never