language: ruby
cache: bundler
rvm:
- 2.1.2
script:
- RAILS_ENV=test bundle exec rake --trace db:create db:migrate
- bundle exec rspec
notifications:
  email:
    recipients:
    - steven.magelowitz@gmail.com
    - evantedesco@gmail.com
    on_failure: change
    on_success: never
env:
  global:
  - secure: XmLqcUHk8PmpSoerizgIaRW0NFDbAC08oxALdJYBpIe8fJ9+741IGBCIlEN/f0OvPs3YMIvQZV7lgLkSTtIR1HlZ4TGpnOJHYIzjBfEoOakpyOL66J/53wTczwP380k+nbLJHWP7lA2doSaqC+SYbcn2LoVh+Gk/xcE9GpqgNug=
  - secure: GakXRuQvrZe/tgcAct2YwojZqxKE4uLlPfeeX6EdExAFAP9vSiJZNnQR+CKY7XEsfr/nVWGTuOvg8TWXEtZHhwDQJoiYeXYvLMKI+ODHB1Px4xel7nTOKb3OSPx1K3HVp3x56n4/2KHrEMtIt3U4Cg6Oq0rGgJEvUjRzp+xdJm4=
  - secure: TA24zAHavFwSHPq67FUjvbnBC+g6lvDYDYOM0pqWKb+WyonaGGfx8D7P14lMm8tzDmcFQKB4EmjFSEcZH2M4PHlc6/TmPvuhwXq1FLSXVr91bOsXvrMMfCg9LEXnNOUx3C2Bn3RAzzbqtJ7NISYVtVj6saIcGlKoY6OlbA16qIo=
