language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - steven.magelowitz@gmail.com
    on_failure: change
    on_success: never